# Generated by Django 5.0.6 on 2024-06-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default='Admin', max_length=50),
        ),
    ]
